### ISSUE TITLE
cios login で、slice bounds out of range が起きる

### ISSUE THREAD

**Issue by syun03** [optim-corp/cios-cli#25]
エラーの内容
```
$ cios login
? Choose a stage: viola
? Redirect URI:  http://localhost/
? Client ID:  xxxxxxxxxx-xxxxxxxxxx-xxxxxxxxxx-xxxxxxxxxx-xxxxxxxxxx
? Client Secret ****************************************************************
auth.pre.cios.dev
panic: runtime error: slice bounds out of range [:21] with length 17

goroutine 1 [running]:
github.com/optim-corp/cios-cli/cli/authorization.login()
        C:/Users/kazuhiro.seida/work/git/github/cios-cli/cli/authorization/login.go:98 +0x753
github.com/optim-corp/cios-cli/cli/authorization.GetLoginCommand.func1(0xc0000c1280, 0x2, 0x2)
        C:/Users/kazuhiro.seida/work/git/github/cios-cli/cli/authorization/login.go:44 +0x68
github.com/urfave/cli/v2.(*Command).Run(0xc000188d80, 0xc0000c1080, 0x0, 0x0)
        C:/Users/kazuhiro.seida/go/pkg/mod/github.com/urfave/cli/v2@v2.2.0/command.go:164 +0x4ed
github.com/urfave/cli/v2.(*App).RunContext(0xc000082480, 0xc49640, 0xc0000ba040, 0xc0000ae020, 0x2, 0x2, 0x0, 0x0)
        C:/Users/kazuhiro.seida/go/pkg/mod/github.com/urfave/cli/v2@v2.2.0/app.go:306 +0x81f
github.com/urfave/cli/v2.(*App).Run(...)
        C:/Users/kazuhiro.seida/go/pkg/mod/github.com/urfave/cli/v2@v2.2.0/app.go:215
main.main()
        C:/Users/kazuhiro.seida/work/git/github/cios-cli/main.go:96 +0x788
```

**Comment by syun03** [comment]
https://github.com/optim-corp/cios-cli/pull/27/ にて pull request

**Comment by optim-yusuke-aoki** [comment]
Closed MergeRequest
